# Generated by Django 4.2.6 on 2023-10-17 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='место выполнения')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='время начала выполнения')),
                ('action', models.TextField(verbose_name='действие, которое представляет из себя привычка ')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodicity', models.CharField(choices=[('daily', 'ежедневно'), ('sunday', 'воскресенье'), ('monday', 'понедельник'), ('tuesday', 'вторник'), ('wednesday', 'среда'), ('thursday', 'четверг'), ('friday', 'пятница'), ('saturday', 'суббота')], default='daily', max_length=20, verbose_name='периодичность выполнения')),
                ('reward', models.TimeField(verbose_name='вознаграждение')),
                ('duration', models.DurationField(verbose_name='продолжительность выполнения в минутах')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
    ]
