# Generated by Django 4.2.6 on 2023-10-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_rename_las_try_habit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата и время последней отправки'),
        ),
    ]
