# Generated by Django 4.2.6 on 2023-10-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.SmallIntegerField(auto_created=1, default=1, verbose_name='периодичность выполнения в днях'),
        ),
    ]
