# Generated by Django 4.2.6 on 2023-10-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(verbose_name='время начала выполнения'),
        ),
    ]
