# Generated by Django 4.2.6 on 2023-10-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.TextField(blank=True, null=True, verbose_name='вознаграждение'),
        ),
    ]
