# Generated by Django 4.2.6 on 2023-10-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='периодичность выполнения в днях'),
        ),
    ]
