# Generated by Django 4.2.6 on 2023-10-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='las_try',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата и время последней отправки'),
        ),
    ]
